apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-a
  labels:
    app: weather-forecast-a
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp-a
  template:
    metadata:
      labels:
        app: weather-forecast-a
        service: webapp-a
    spec:
      containers:
        - name: webapp-a
          image: demoregistrygodoy.azurecr.io/demopipeline:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: WebApiBaseAddress
              value: http://webapi
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-a
  labels:
    app: weather-forecast-a
    service: webapp-a
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp-a